services:
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb_${APP_NAME}
    restart: always
    user: "999:999"  # UID:GID untuk user mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?MYSQL_DATABASE is required}
      MYSQL_USER: ${MYSQL_USER:?MYSQL_USER is required}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is required}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network
    # healthcheck:
    #   test: ["CMD-SHELL", "mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1' || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  wordpress:
    image: wordpress:php8.2-apache
    container_name: web_${APP_NAME}
    restart: always
    user: "33:33"  # UID:GID untuk user www-data
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:?MYSQL_USER is required}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is required}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:?MYSQL_DATABASE is required}
    ports:
      - "127.0.0.1:${PORT:-80}:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin_${APP_NAME}
    restart: always
    user: "33:33"  # UID:GID untuk user www-data
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: ${UPLOAD_LIMIT:-100M}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    networks:
      - wp-network

volumes:
  db_data:
  wordpress_data:

networks:
  wp-network: